taskly_ironhack_authentication-master/config/routes.rb
Rails.application.routes.draw do
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  match '/signup',    to: 'users#new',    via: 'get'

  resources :users
  resources :tasks

  namespace :api do
    namespace :v1 do
      resources :users, except: [:new, :edit] do
        resources :tasks, except: [:new, :edit]
        post 'tasks/:id/complete', to: 'tasks#complete'
      end
    end
  end

end

taskly_ironhack_authentication-master/app/models/api/v1.rb
module Api::V1
  def self.table_name_prefix
    'api_v1_'
  end
end

taskly_ironhack_authentication-master/app/models/api/v1/task.rb
class Api::V1::Task < ActiveRecord::Base
end

taskly_ironhack_authentication-master/app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user

	validates :name,  		presence: true, length: { maximum: 250 }
	validates :due_date, 	presence: true
	validates :user_id, 	presence: true


	def complete!
		self.complete = true
		self
	end

	def as_json(options={})
	  super(except: [ :created_at, :updated_at])
	end
end

taskly_ironhack_authentication-master/app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }

	validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }



	has_many :tasks

	has_secure_password




	def as_json(options={})
  	super( only: [:name,:email],
    	methods: [:tasks_count],
    	include: [tasks:  { only: :name }])
	end

	def tasks_count
		self.tasks.count
	end
end

taskly_ironhack_authentication-master/app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < ApplicationController
	before_action :user_exists

	def index
		tasks = @user.tasks
		render json: tasks
	end


	def create
		task = @user.tasks.build(task_params)
		task.save
		render json: task
	end

	def show
		task = @user.tasks.find_by(id: params[:id])
		unless task
			render json: { error: "task not found"}, status: 400
			return
		end
		render json: task
	end

	def complete
		task = @user.tasks.find_by(id: params[:id])
		unless task
			render json: { :error => "task not found"}, status: 400
			return
		end
		task.complete! 
		task.save
		render json: task
	end

	private

	def task_params
		params.require(:task).permit(:name, :due_date)
	end

	def user_exists
	  @user = User.find_by(id: params[:user_id])
		unless @user
			render json: { error: "user not found"}, status: 400
			return
		end 
	end
end

taskly_ironhack_authentication-master/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
	def index
		users = User.all
		render json: users
	end


	def create
		user = User.create(user_params)
		render json: user, except: [:id] 
	end

	def show
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		render json: user
	end

	def update
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		user.update(user_params)
		render json: user
	end

	def destroy
		user = User.find_by(id: params[:id])
		unless user
			render json: { error: "user not found"}, status: 400
			return
		end
		user.destroy
		render json: user
	end


	private

	def user_params
		params.require(:user).permit(:name, :email)
	end

end

taskly_ironhack_authentication-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :signed_in_user
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  unless Rails.env.development?
  	protect_from_forgery with: :exception
  end
  include SessionsHelper


  private

  	def signed_in_user
    	unless current_user
        redirect_to login_path, notice: 'Access forbidden.'
      end
    end
  
end

taskly_ironhack_authentication-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :signed_in_user, only: [:new, :create]

  def new

  end

def create    
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    redirect_to user
  else
    redirect_to '/login'
  end
end


  def destroy
  	session.clear
  	redirect_to '/login'
  end
end

taskly_ironhack_authentication-master/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :current_user_is_the_owner, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :due_date, :completed, :user_id)
    end

    def current_user_is_the_owner
      @task = Task.find(params[:id])
      @user = @task.user
      unless current_user.id == @user.id 
        redirect_to tasks_path, notice: 'Access forbidden.'
      end
    end
end

taskly_ironhack_authentication-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :signed_in_user, only: [:new, :create]
  before_action :user_is_current_user, only: [:edit, :update]
  # GET /users
  def index
    @users = User.all
    UserMailer.welcome(current_user).deliver_now
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1

  private
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_controller)
    end

    def user_is_current_user
      @user = User.find(params[:id])
      unless current_user.id == @user.id 
        redirect_to users_path, notice: 'Access forbidden.'
      end
    end


end

taskly_ironhack_authentication-master/app/helpers/api/v1/tasks_helper.rb
module Api::V1::TasksHelper
end

taskly_ironhack_authentication-master/app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
	def logged_in?
    !current_user.nil?
  end


end

taskly_ironhack_authentication-master/app/helpers/users_helper.rb
module UsersHelper
end

taskly_ironhack_authentication-master/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

taskly_ironhack_authentication-master/app/views/users/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

taskly_ironhack_authentication-master/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

taskly_ironhack_authentication-master/app/views/users/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

taskly_ironhack_authentication-master/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>