timetracking/config/routes.rb
Rails.application.routes.draw do
  root to: 'site#home'
  
  resources :projects, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  	resources :entries, only: [:index, :new, :create, :destroy, :edit, :update] 
  end

  # get 'contact'=> 'site#contact'
  # get 'projects' => 'projects#index'
  # get 'projects/new' => 'projects#new'
  # post 'projects' => 'projects#create'
  # get 'projects/:id' => 'projects#show', as: 'project'
  # get 'projects/:id/edit' => 'projects#edit'
  # patch 'projects/:id' => 'projects#update'
  # delete 'projects/:id' => 'projects#destroy'
  # get 'projects/:project_id/entries' => 'entries#index'
  # get 'projects/:project_id/entries/new' => 'entries#new'
end

timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	validates :hours, numericality: true
	validates :minutes, numericality: {only_integer: true, greater_than: 0}
	validates :date, :hours, :minutes, presence: true
	validates :project_id, presence: true

	belongs_to :project
end

timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, uniqueness: true
	validates :name, presence: true
	validates :name, length: {maximum: 30}
	validates :name, format: {with: /[a-zA-Z0-9_ ]*/ }

	has_many :entries

	def self.iron_find (id)
		where(id: id).first
	end

	def self.clean_old
		date=Time.now.midnight - 1.week
		projects=where("created_at<?",date)
		projects.destroy_all
	end

	def self.last_created_projects(n)
		limit(n).order("created_at DESC")
	end

	def how_many_hours
		time=entries.reduce(0) do |sum,x|
			sum+x.hours.to_f+((x.minutes.to_f)/60).round(2)
		end
		time.round(2)
	end
	def how_many_hours_this_month(month,year)
		time=entries.reduce(0) do |sum,entry|
			sum+entry.hours.to_f+((entry.minutes.to_f)/60).round(2) if entry.created_at.month==month && entry.created_at.year==year
		end
		time.round(2)
	end
	def entries_this_month(month,year)
		entries.where(created_at: Date.new(year,month,1)..Date.new(year,month,-1))
		# self.entries.each do |entry|
		# 	entry.
		# end
	end
	def how_many_hours_Quino(filtered_entries)
		entries_to_search = filtered_entries
		hours = entries_to_search.sum(:hours)
		minutes = entries_to_search.sum(:minutes)
		hours += minutes/60
	end

	def entries_this_month_Quino(month, year)
		date=Date.new(year,month)
		filtered_entries = entries.where(date: date.all_month)
	end
	def total_hours_this_month_Quino(month, year)
		how_many_hours_Quino(entries.entries_this_month_Quino(month, year))
	end
end

timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@project=Project.find(params[:project_id])
		@entries=@project.entries
		@entries_this_month=@project.entries_this_month(Time.now.month,Time.now.year)
		@total_hours=@project.how_many_hours
		@total_hours_this_month=@project.how_many_hours_this_month(Time.now.month,Time.now.year)
	end

	def new
		@project = Project.find(params[:project_id])
		@entry = @project.entries.new
	end

	def create
		@project = Project.find(params[:project_id])
		@entry = @project.entries.new(entry_params)
		if @entry.save
			flash[:notice] = "Entry created successfully"
			redirect_to project_entries_path(@project)
		else
			flash.now[:alert] = "Uh oh! Something went wrong"
			render "new"
		end
	end

	def edit
		@project = Project.find(params[:project_id])
		@entry = @project.entries.find(params[:id])
	end

	def update
		@project = Project.find(params[:project_id])
		@entry = @project.entries.find(params[:id])
		@entry.update_attributes(entry_params)
		if @entry.update_attributes(entry_params)
			flash[:notice] = "Entry updated!"
			redirect_to project_entries_path(@project)
		else
			@errors = @entry.errors.full_messages
			render :edit
		end
	end		

	def destroy
		project=Project.find(params[:project_id])
		entry=project.entries.find(params[:id])
		entry.destroy

		redirect_to project_entries_path(project.id)
	end
	
	private
	
	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date, :comments)
	end

end

timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	def index
		@projects = Project.last_created_projects(30)
	end

	def new
		@project = Project.new
	end

	def create
		p = Project.new(name: params[:project][:name], description: params[:project][:description])
		p.save
		redirect_to '/projects'
	end

	def show
		@project=Project.find(params[:id])
		rescue ActiveRecord::RecordNotFound
		render 'no_hay_nada'
	end

	def edit
		@project=Project.find(params[:id])
	end

	def update
		new_project = params[:project]
		name = new_project[:name]
		description = new_project[:description]
				
		@project=Project.find(params[:id])
		@project.update_attributes(name: name, description: description)
		redirect_to '/projects'
	end

	def destroy
		project=Project.find(params[:id])
		project.destroy

		redirect_to '/projects'
	end
end

timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render 'home' #name of view template
	end
	def contact
		# render 'contact'
	end
end

timetracking/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_message
		display_message(:alert) || display_message(:notice)
	end
		# if flash[:alert]
		# 	content_tag :div, class: "message alert" do
		# 		content tag :p do
		# 			flash[:alert]
		# 		end
		# 	end
		# elsif flash[:notice]
		# 	content_tag :div, class: "message notice" do
		# 		content tag :p do
		# 			flash[:notice]
		# 		end
		# 	end
		# end

	
		
	def display_message type
		if flash[type]
			content_tag :div, class: type do
				content_tag :p do
					flash[type]
				end
			end
		end
	end

end

timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

timetracking/app/helpers/site_helper.rb
module SiteHelper
end

timetracking/app/views/entries/_form.html.erb
<%= form_for [@project, @entry] do |f| %>
	<%=f.label :hours , "Hours:" %>
	<%= f.number_field :hours %>
	<%= f.label :minutes , "Minutes:" %>
	<%= f.number_field :minutes %>
	<%= f.label :comments , "Coments:" %>
	<%= f.text_field :comments %>
	
	<%= f.label :date , "Date:" %>
	<%= f.date_field :date %>
	
	<%= f.submit "Save" %>
<% end %>

timetracking/app/views/entries/edit.html.erb
<h1>Edit entry for project: <%= @project.name %></h1>

<% if @errors.present? %>
	<ul>
		<% @errors.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<%= render "form" %>

<%= link_to "Cancel", project_entries_path %>

timetracking/app/views/entries/index.html.erb
<h1>Project: <%= @project.name %></h1>
<h2>Total hours worked: <%= @total_hours %> </h2>
<h2>Total hours worked this month: <%= @total_hours_this_month %> </h2>
<%=flash_message %>

<h3>Entries</h3>

<ul>
	<% @entries_this_month.each do |entry| %>
	<li><%= entry.id %> - <%= entry.hours %>:<%= entry.minutes %>
		<%= entry.comments.present? ? "- #{entry.comments}" : " " %>
		<%= link_to "Edit", edit_project_entry_path(@project,entry) %>
		<%= link_to "Delete", project_entry_path(@project,entry), method: :delete, data: {confirm: "Are you sure?"} %>
	</li>
	<% end %>

	<%= link_to "Create new entry", new_project_entry_path %>
	<br>
	<%= link_to "Back to projects", projects_path %>
</ul>

timetracking/app/views/entries/new.html.erb
<h1>New entry for project: <%= @project.name %></h1>
<h2><%=flash_message %></h2>
<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_message| %>
		<li><%= error_message %></li>
		<% end %>
	</ul>
<% end %>
		
<%= render "form" %>

<%= link_to "Cancel", project_entries_path %>

timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

timetracking/app/views/projects/edit.html.erb
<%= form_for @project do |f| %>
	<%=f.label :name , "Name:" %>
	<%= f.text_field :name %>
	<%= f.label :description , "Description:" %>
	<%= f.text_field :description %>

	<%= f.submit "Update" %>
<% end %>

timetracking/app/views/projects/index.html.erb
<h1>Welcome to Timetracking tool</h1>
<h3>Projects</h3>
<ul>
	<% @projects.each do |project| %>
	<li><%= project.id %> - <%= link_to project.name, project_path(project.id) %>
		<%= project.description.present? ? "- #{project.description}" : " " %>
		<%=link_to("Entries", project_entries_path(project)) %>
		<%= link_to("Delete", project_path(project.id), method: :delete) %>
	</li>
	<% end %>
</ul>

timetracking/app/views/projects/new.html.erb
<%= form_for @project do |f| %>
	<%=f.label :name , "Name:" %>
	<%= f.text_field :name %>
	<%= f.label :description , "Description:" %>
	<%= f.text_field :description %>

	<%= f.submit "Save" %>
<% end %>

timetracking/app/views/projects/no_hay_nada.html.erb
<h1>Aquí no hay nada!!</h1>

timetracking/app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h2><%= @project.description %></h2>

timetracking/app/views/site/contact.html.erb
<h1>Contact:</h1>
<a href="mailto:contact@example.com">contact@example.com</a>

timetracking/app/views/site/home.html.erb
<h1>Hello</h1>
<p>Welcome to my timetracking tool</p>